### ISSUE TITLE
Is there any Best Practices Workflow for gene panel germline variants calling ?

### ISSUE THREAD

**Issue by woodword** [gatk-workflows/gatk4-germline-snps-indels#26]
Dear workflow developer
I started to use GATK not long ago. My lab is doing research on some specific inheritable diseases, so instead of whole genome/exome sequencing the most of the data is from small gene panels ( < 10 genes ). But according to the workflow introduction, the two joint discovery workflows do not support gene panels.

What should I do ? Should I still try the original joint-discovery-gatk4-local.wdl workflow or anything else ?

**Comment by bshifaw** [comment]
Hi @woodword 

Thanks for you question. I wouldn't suggest the using either of joint-disocvoery workflow in this repo since both indicate they do not support gene panels. Best thing to do is ask the team on the [GATK forum](https://gatkforums.broadinstitute.org/gatk), and use their suggestion to modify the workflow to process gene panels.
